"use client";

import { useMemo } from "react";
import { useConnection, useWallet } from "@solana/wallet-adapter-react";
import { AnchorProvider, Program, type Idl } from "@coral-xyz/anchor";
import { PROGRAM_IDS } from "@/lib/constants";

// IDLs are generated by `anchor build` and resolved via the @idl webpack alias.
// Run `anchor build` from workspace root, then `npm run copy:idl` from /app.
function tryLoadIdl(name: string): Idl | null {
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    return require(`@idl/${name}.json`) as Idl;
  } catch {
    return null;
  }
}

const WorkerRegistryIdl  = tryLoadIdl("worker_registry");
const PayrollVaultIdl    = tryLoadIdl("payroll_vault");
const EscrowManagerIdl   = tryLoadIdl("escrow_manager");
const ComplianceLogIdl   = tryLoadIdl("compliance_log");

export type Programs = {
  provider:        AnchorProvider;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  workerRegistry:  Program<any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  payrollVault:    Program<any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  escrowManager:   Program<any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  complianceLog:   Program<any>;
};

export function usePrograms(): Programs | null {
  const { connection } = useConnection();
  const wallet = useWallet();

  return useMemo(() => {
    if (
      !wallet.publicKey ||
      !wallet.signTransaction ||
      !WorkerRegistryIdl ||
      !PayrollVaultIdl   ||
      !EscrowManagerIdl  ||
      !ComplianceLogIdl
    ) {
      return null;
    }

    const provider = new AnchorProvider(
      connection,
      wallet as Parameters<typeof AnchorProvider>[1],
      { commitment: "confirmed", preflightCommitment: "confirmed" }
    );

    return {
      provider,
      workerRegistry: new Program(WorkerRegistryIdl,  PROGRAM_IDS.workerRegistry, provider),
      payrollVault:   new Program(PayrollVaultIdl,    PROGRAM_IDS.payrollVault,   provider),
      escrowManager:  new Program(EscrowManagerIdl,   PROGRAM_IDS.escrowManager,  provider),
      complianceLog:  new Program(ComplianceLogIdl,   PROGRAM_IDS.complianceLog,  provider),
    };
  }, [connection, wallet]);
}
